### ISSUE TITLE
US11 - Acionar equipe

### ISSUE THREAD

**Issue by drianne** [PI2-viticultura/SmartVit#2]
**Descrição**

Funcionalidade a partir do qual o usuário poderá solicitar suporte da SmartVit, seja devido os sistemas eletrônicos instalados ou devido problemas com o software.

**Tarefas**

- [x] Criar endpoint 
- [x] Criar tela
- [x] Conectar frontend ao backend
- [x] Armazenar dados no banco de dados.

**Critérios de aceitação**

- [x] O layout deve seguir o estabelecido por meio do protótipo
- [x] A solicitação de suporte deve ser armazenada no banco de dados

**Comment by jlucassr** [comment]
Como a US já foi aprovada e merjado, considerai como issue concluída. 
Parabéns aos envolvidos.
