### ISSUE TITLE
US19 - Definir ML

### ISSUE THREAD

**Issue by drianne** [PI2-viticultura/SmartVit#39]
**Descrição**

Definir dataset e qual estudo será realizado com ele.

**Tarefas**

- [ ] Definir dataset
- [ ] Definir ML a ser aplicado 

**Critérios de aceitação**

- [ ] Documentar dataset escolhido
- [ ] Documentar tipo de estudo a ser realizado

**Comment by drianne** [comment]
Será utilizada uma base de dados que relaciona características fisicoquímicas do vinho com a classificação da qualidade dele, feita por especialistas da área. Essa classificação será utilizada para julgar a qualidade da atuação da smartvit. Serão relacionadas as seguintes variáveis: 

Input variables (based on physicochemical tests):
1 - fixed acidity
2 - volatile acidity
3 - citric acid
4 - residual sugar
5 - chlorides
6 - free sulfur dioxide
7 - total sulfur dioxide
8 - density
9 - pH
10 - sulphates
11 - alcohol
Output variable (based on sensory data):
12 - quality (score between 0 and 10)

Dataset: https://archive.ics.uci.edu/ml/datasets/wine+quality 
ML: O problema se configura como um problema de classificação com provavelmente o algorítmo SGD classifier (https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html)

**Comment by drianne** [comment]
@Lucas362 valida pra mim, pfv

**Comment by Lucas362** [comment]
Totalmente de acordo
